#!/usr/bin/env php
<?php

$numbers = array(3, 4, 9, 14, 15, 19, 28, 37, 47, 50, 54, 56, 59, 61, 70, 73, 78, 81, 92, 95, 97, 99);
$nb = 0;

foreach ($numbers as $index => $sum) {
    if ($index < 5) {
        continue;
    }
    $candidates = array_slice($numbers, 0, $index);
    foreach ($candidates as $a) {

    }
    var_dump($sum, implode(', ', $candidates));die;
}
/*
XXXX
  11 2+3
 1 1 1+3
 11  1+2
 111 1+2+3
1  1 0+3
1 1  0+2
1 11 0+2+3
11   0+1
11 1 0+1+3
111  0+1+2
1111 0+1+2+3
 */
